// <auto-generated />
namespace Cygnet.EmployeeOnboardingApp.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Details : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Details));
        
        string IMigrationMetadata.Id
        {
            get { return "201806080644181_Details"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
